# tfsec configuration
# Best practice: Configure security scanning to catch vulnerabilities early

# Severity levels: CRITICAL, HIGH, MEDIUM, LOW
minimum_severity: MEDIUM

# Exclude specific checks (add check IDs to ignore)
exclude:
  # Example: Exclude specific checks
  # - aws-s3-enable-bucket-logging
  # - aws-ec2-enforce-http-token-imds

# Exclude specific directories
exclude_paths:
  - .terraform/
  - .git/

# Output format: default, json, csv, sarif, junit
format: default

# Soft fail mode (don't exit with error code)
soft_fail: false

# Include passed checks in output
include_passed: false

# Include ignored checks in output
include_ignored: false

# Disable colored output
no_colour: false

# Concise output
concise_output: false

# Custom severity overrides (optional)
# severity_overrides:
#   aws-s3-enable-bucket-encryption: ERROR
#   aws-ec2-enforce-http-token-imds: WARNING

# Best practices:
# 1. Set minimum_severity based on your security requirements
# 2. Review and document any excluded checks
# 3. Run tfsec in CI/CD pipeline
# 4. Regularly update tfsec to get new security rules
# 5. Use SARIF format for integration with GitHub Security tab
